name: Release Helm Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: actions/setup-helm@v3
        with:
          version: '3'

      - name: Build Helm charts
        run: |
          helm lint charts/
          helm package charts/

      - name: Upload Helm charts to GitHub Releases
        uses: actions/upload-artifact@v3
        with:
          name: helm-charts
          path: '*.tgz'

      - name: Create Helm chart repository index
        run: |
          helm repo index charts --url https://Jedi-5.github.io/helm/charts --force

      - name: Upload index.yaml to GitHub Releases
        uses: actions/upload-artifact@v3
        with:
          name: index.yaml
          path: index.yaml

      - name: Create GitHub Release
        uses: actions/create-github-release@v3
        with:
          release_name: ${{ github.event.release.tag_name }}
          asset_paths: ./index.yaml,'**/helm-charts/*.tgz'
          draft: false
          prerelease: false
